#!/usr/bin/env bash

#
# Package Config

unset SHELLNS_MANUAL_SELECT_SHOW_SECTION
declare -gA SHELLNS_MANUAL_SELECT_SHOW_SECTION
SHELLNS_MANUAL_SELECT_SHOW_SECTION["s"]="summary"
SHELLNS_MANUAL_SELECT_SHOW_SECTION["d"]="description"
SHELLNS_MANUAL_SELECT_SHOW_SECTION["p"]="parameters"
SHELLNS_MANUAL_SELECT_SHOW_SECTION["r"]="return"

unset SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION
declare -gA SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION
SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION["s"]="summary"
SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION["d"]="description"
SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION["t"]="type"
SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION["p"]="properties"



#
# Collection of placeholders for colorization of manuals.
unset SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER
declare -gA SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{NONE}}"]="\e[0m"

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{HEADER}}"]="\e[1;38;5;68;48;5;234m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{FOOTER}}"]="\e[1;38;5;68;48;5;234m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TEXT}}"]="\e[0m"

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{LIST_BULLET}}"]="\e[1;90m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{LIST_TEXT}}"]="\e[0;37m"

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{CODE_BLOCK_SIGN}}"]="\e[1;38;5;68m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{CODE_BLOCK_LANG}}"]="\e[1;38;5;68m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{CODE_BLOCK_COMMENT}}"]="\e[2;38;5;252m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{CODE_BLOCK_TEXT}}"]="\e[37m"

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{SUBSECTION_AT}}"]="\e[1;94m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{SUBSECTION_NAME}}"]="\e[90m"

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_DOLLAR}}"]="\e[1;94m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_NUMBER}}"]="\e[90m"

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_SIGN_BLOCK}}"]="\e[1;94m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_LIST_INDENT}}"]="  "
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_LIST_BULLET}}"]="\e[37m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_LIST_KEY}}"]="\e[90m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_LIST_COLON}}"]="\e[37m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_LIST_VALUE}}"]="\e[96m"

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TYPE_SIGN_SEPARATOR}}"]="\e[1;34m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TYPE_SIGN_NULLABLE}}"]="\e[1;94m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TYPE_SIGN_PLUS}}"]="\e[1;34m"
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TYPE_NAME}}"]="\e[90m"



#
# Collection of all placeholders defined in 'SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER'.
unset SHELLNS_MANUAL_PLACEHOLDER_NAME_COLLECTION
declare -ga SHELLNS_MANUAL_PLACEHOLDER_NAME_COLLECTION=()
for k in "${!SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER[@]}"; do
  SHELLNS_MANUAL_PLACEHOLDER_NAME_COLLECTION+=("${k}")
done
unset k



unset SHELLNS_MANUAL_COLOR_MAPPING_FONT_REPLACE
declare -gA SHELLNS_MANUAL_COLOR_MAPPING_FONT_REPLACE
SHELLNS_MANUAL_COLOR_MAPPING_FONT_REPLACE["SHELLNS_FONT_INLINE_BLOCK_IN"]="\e[1;37;48;5;245m"
SHELLNS_MANUAL_COLOR_MAPPING_FONT_REPLACE["SHELLNS_FONT_INLINE_BLOCK_OUT"]="\e[0m"