#!/usr/bin/env bash

#
# Package Config

unset SHELLNS_MANUAL_SELECT_SHOW_SECTION
declare -gA SHELLNS_MANUAL_SELECT_SHOW_SECTION
SHELLNS_MANUAL_SELECT_SHOW_SECTION["a"]="all"
SHELLNS_MANUAL_SELECT_SHOW_SECTION["s"]="summary"
SHELLNS_MANUAL_SELECT_SHOW_SECTION["d"]="description"
SHELLNS_MANUAL_SELECT_SHOW_SECTION["p"]="parameters"
SHELLNS_MANUAL_SELECT_SHOW_SECTION["r"]="return"

unset SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION
declare -gA SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION
SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION["a"]="all"
SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION["s"]="summary"
SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION["d"]="description"
SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION["t"]="type"
SHELLNS_MANUAL_SELECT_SHOW_SUBSECTION["p"]="properties"



#
# Collection of placeholders for colorization of manuals.
unset SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER
declare -gA SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{NONE}}"]="\e[0m"

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TEXT}}"]=""

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{CODE_BLOCK_SIGN}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{CODE_BLOCK_COMMENT}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{CODE_BLOCK_TEXT}}"]=""

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{LIST_BULLET}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{LIST_TEXT}}"]=""

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{SUBSECTION_AT}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{SUBSECTION_NAME}}"]=""

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_DOLLAR}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_NUMBER}}"]=""

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_SIGN_BLOCK}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_LIST_INDENT}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_LIST_KEY}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_LIST_COLON}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{PARAM_PROP_LIST_VALUE}}"]=""

SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TYPE_SIGN_SEPARATOR}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TYPE_SIGN_NULLABLE}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TYPE_SIGN_PLUS}}"]=""
SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER["{{TYPE_NAME}}"]=""




#
# Collection of all placeholders defined in 'SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER'.
unset SHELLNS_MANUAL_PLACEHOLDER_NAME_COLLECTION
declare -ga SHELLNS_MANUAL_PLACEHOLDER_NAME_COLLECTION=()
for k in "${!SHELLNS_MANUAL_COLOR_MAPPING_PLACEHOLDER[@]}"; do
  SHELLNS_MANUAL_PLACEHOLDER_NAME_COLLECTION+=("${k}")
done
unset k